[vaproh.xyz]
source        = imaps://contact@vaproh.xyz:<password>@imap.titan.email
outgoing      = smtps://contact@vaproh.xyz:<password>@smtp.titan.email
default       = INBOX
from          = Vaproh <contact@vaproh.xyz>
cache-headers = true

