[vaproh.xyz]
source        = imaps://contact@vaproh.xyz:Slayer129@@imap.titan.email
outgoing      = smtps://contact@vaproh.xyz:Slayer129@@smtp.titan.email
default       = INBOX
from          = Vaproh <contact@vaproh.xyz>
cache-headers = true

