# Auto‑generated Pywal16 kitty theme
# ────────────────────────────────────────────

foreground   #c2c5c7
background   #001a2c
cursor       #c2c5c7

# 16 ANSI colors
color0       #001a2c
color1       #d5247c
color2       #ed5d00
color3       #fe9b0c
color4       #ffa536
color5       #006c9c
color6       #007ada
color7       #c2c5c7

color8       #1472b8
color9       #d5247c
color10      #ed5d00
color11      #fe9b0c
color12      #ffa536
color13      #006c9c
color14      #007ada
color15      #c2c5c7

# borders & tabs (optional)
inactive_border_color       #373B41
bell_border_color           #CC6666
active_border_color         #81A2BE
active_tab_foreground       #1D1F21
active_tab_background       #C5C8C6
inactive_tab_foreground     #969896
inactive_tab_background     #282A2E


