#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat

    touchpad {
        natural_scroll = true
        middle_button_emulation = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    # workspace_swipe removed or unsupported in this Hyprland version
}

device {
}
