;==========================================================
[gruvbox]
black= #000000
dark= #222222
disabled= #504945
red= #ea6962
red-alt= #b22222
orange= #fe8019
orange-mat=#e78a4e
yellow= #fabd2f
yellow-mat=#d8a657
green= #b8bb26
green-alt=#98971a
aqua= #8ec07c
aqua-alt= #689d6a
blue= #458588
blue-alt=#83a598
grey= #504945
dark-grey=#1d2021
cream= #fff4d2
white= #FFFFFF
transparent= #00000000
Stransparent= #CC000000

;==========================================================
[onedark]
black= #3f4451
dark= #4f5666
disabled= #d7dae0
red= #e05561
red-alt= #ff616e
orange= #d19a66
orange-mat= #e78a4e
yellow= #e5c07b
yellow-mat= #f0a45d
green= #8cc265
green-alt= #a5e075
aqua= #8ec07c
aqua-alt= #689d6a
blue= #4aa5f0
blue-alt= #4dc4ff
cyan= #42b3c2
cyan-alt= #4cd1e0
magenta= #c678dd
pink= #f4b8e4
grey= #2c313a
dark-grey=#1d2021
cream= #e6e6e6
white= #d7dae0
transparent= #00000000
Stransparent= #CC000000
bg= #23272e
fg= #abb2bf
